spring:
  application:
    name: oauth-server

server:
  port: 8071
  context-path: /spring-security-oauth-server

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://119.40.98.167:8751/eureka/
  instance:
    hostname: localhost